/* Bilingual article copy. Keep the Chinese HTML fallback in sync. */
window.GANDER_BLOG = {
  "strings": {
    "zh": {
      "title": "Gander：全模态交互智能体",
      "subtitle": "融合全模态感知、实时对话与异步任务执行，让智能体在交流中理解需求、推进任务。",
      "meta.description": "通过十二个演示，了解 Gander 如何结合语音、视觉与实时对话完成智能体任务，并介绍大脑—小脑架构、交互数据构建及实验评估。",
      "nav.home": "项目主页",
      "nav.paper": "技术报告",
      "nav.label": "站点导航",
      "breadcrumb.home": "Gander",
      "breadcrumb.blog": "技术博客",
      "kicker": "GANDER · 技术博客",
      "skip": "跳至文章正文",
      "lang.label": "文章语言",
      "lang.zh": "切换为中文",
      "lang.en": "Switch to English",
      "meta.dateLabel": "报告日期",
      "meta.date": "2026 年 9 月 8 日",
      "meta.categoryLabel": "分类",
      "meta.category": "全模态交互智能体",
      "meta.byLabel": "研究团队",
      "meta.by": "混元语音团队（研究项目）",
      "toc.title": "本文目录",
      "toc.label": "文章目录",
      "principle.see.title": "理解不断变化的环境。",
      "principle.see.body": "结合声音与画面理解场景，并在相关视觉事件出现时主动提醒。",
      "principle.talk.title": "把握自然交流的节奏。",
      "principle.talk.body": "在说话的同时听取用户反馈，区分附和、打断与无关干扰，决定继续讲述还是停下来倾听。",
      "principle.act.title": "让任务执行与对话同步进行。",
      "principle.act.body": "后台处理复杂任务时，用户仍可通过语音交流和共享画面补充要求、确认细节或查询进度。",
      "figure.overview.caption": "图 1｜Gander 的主要能力：在持续的多模态交流中理解用户，并异步执行任务。",
      "figure.overview.alt": "Gander 的能力概览，包括屏幕理解、边聊边执行任务、附和与打断、抗干扰对话和视觉事件提醒。",
      "figure.architecture.caption": "图 2｜前端小脑、智能体编排运行时与后端大脑的分工及信息交换。",
      "figure.architecture.alt": "大脑—小脑架构：前端接收用户的音视频输入，编排运行时协调后台任务，各组件共享任务状态、上下文与记忆。",
      "figure.thinker-talker.caption": "图 4｜流式 Thinker–Talker 在统一时间线上组织感知输入、交互决策、文本与语音输出。",
      "figure.thinker-talker.alt": "流式 Thinker–Talker 架构图，展示音视频输入、交互控制、文本生成、语音 token 与波形输出的时间关系。",
      "note.streaming": "一秒是流式处理单元的时长，128 个时间块是模型保留的上下文范围。这些数值描述的是架构配置，并非实测的端到端响应延迟。",
      "video.error": "视频暂时无法播放，请尝试直接打开。",
      "video.open": "直接打开视频",
      "source.architecture": "架构细节：技术报告第 3.2 节",
      "source.streaming": "流式建模细节：技术报告第 3.3 节",
      "source.training": "数据构建：第 4 节，第 14–18 页",
      "source.results": "实验与评估设置：技术报告第 5 节",
      "table.duplex.caption": "Full-Duplex-Bench v3 · 100 个场景 · 表 3 中的部分指标",
      "table.model": "模型",
      "table.turn": "适时接话率 % ↑",
      "table.interrupt": "提前抢话率 % ↓",
      "table.duplex.note": "Pass@1 的取值范围为 0–1，其余两项以百分比表示。↑ 表示越高越好，↓ 表示越低越好。提前抢话率统计模型在用户说完之前开始回应的比例。",
      "table.omni.caption": "音视频融合增益 · 表 6 中的基准结果",
      "table.benchmark": "基准",
      "table.av": "音频 + 视频 %",
      "table.video": "仅视频 %",
      "table.audio": "仅音频 %",
      "table.gain": "融合增益（百分点）",
      "table.omni.note": "融合增益 = 音视频联合输入准确率 − max(仅视频准确率, 仅音频准确率)，单位为百分点。模型由前端直接输出文本答案，不使用语音合成、ASR 或后端大脑。",
      "end.title": "继续了解 Gander",
      "end.paper": "阅读完整论文",
      "end.demos": "浏览全部演示",
      "footer.blog": "技术博客",
      "footer.top": "回到顶部",
      "heading.intro": "Gander：全模态交互智能体",
      "p.intro.motivation": "与人协作，往往是一边交流，一边观察和行动。我们会在对方说话时附和或打断，也会随着场景变化和任务进展补充新的要求。要让智能体参与这样的协作，感知、对话与任务执行就需要协同进行。",
      "p.intro.position": "Gander 将全模态感知、实时交互与智能体任务执行整合到统一框架中。它持续接收语音、视频和文本，结合用户的口头要求、眼前的画面与后续反馈推进任务，让交流贯穿任务执行过程。核心能力体现在三个方面：",
      "p.perception.context": "用户只需先提出“看到企鹅时告诉我”，Gander 就会持续观察视频，并在企鹅出现时主动提醒。这类交互要求模型记住先前的指令，并在后续画面中识别相应事件。",
      "heading.dialogue": "音视频全双工对话",
      "p.dialogue.duplex": "自然的全双工对话，需要区分附和与打断。用户简短附和时，Gander 继续讲述；用户明确要求停下时，它则暂停回应，把话语权交还给用户。模型在说话的同时听取反馈，并根据用户意图调整回应方式。",
      "p.dialogue.translation": "在版本发布、安全审计和风险讨论等场景中，Gander 持续接收说话内容，并逐步输出另一种语言的译文。以下分别展示中译英和英译中的同声传译过程。",
      "heading.reasoning": "抗干扰、多人对话与简易推理",
      "p.reasoning.demo": "“一直开着冰箱门，能让密闭的房间降温吗？”面对这个日常物理问题，Gander 通过语音说明其中的道理，将推理过程组织成便于听懂的解释。",
      "heading.architecture": "大脑—小脑协作架构",
      "p.architecture.roles": "Gander 采用大脑—小脑协作架构，由三个组件分工配合。前端小脑持续接收音视频输入，负责实时对话和交互决策；后端大脑负责复杂推理、工具调用与耗时较长的任务；智能体编排运行时负责管理任务状态、协调执行，并传递进度与结果。后端大脑支持替换，接入时无需额外训练。",
      "p.architecture.lifecycle": "前端通过 task_start 发起后台任务，通过 task_send 补充要求或查询进度，通过 task_resolve 表达取消、授权等任务操作。编排运行时负责将这些指令落实到具体任务，并把执行进展与结果传回前端。这样，用户在任务进行期间仍可补充条件、调整要求，持续参与整个过程。",
      "heading.streaming": "流式 Thinker–Talker 建模",
      "p.streaming.units": "前端小脑采用流式 Thinker–Talker 架构，以一秒为一个处理单元。每个单元先接收音视频输入，以及当前可用的文本或工具返回结果，再决定聆听、说话、打断或发起结构化工具调用，并按需生成文本。模型保留最近 128 个时间块，形成约两分钟的滑动上下文，使后续回应能够参考新到达的信息。",
      "p.streaming.speech": "Thinker 负责生成文本和交互动作，Talker 根据文本及隐藏状态生成离散语音单元，再由流式解码器合成语音波形。在训练格式中，每个说话单元最多包含八个文本 token，与 50 个 S3 语音 token 对齐。这样的分工使模型能够持续接收输入，同时逐步生成语音。",
      "heading.training": "交互数据构建",
      "p.training.corpus": "Gander 的训练语料约有 270 万条样本，涵盖语音交互、音视频交互、智能体交互，以及抗干扰与负样本四类。训练既关注回答内容，也关注何时接话、如何响应视觉事件，以及怎样处理任务状态的变化。模型由此学习在持续交流中聆听、回应，并与后台任务协调。",
      "heading.evaluation": "交互、语音对话与全模态理解评估",
      "p.evaluation.duplex": "基准测试从交互时机和任务完成情况两个方面评估全双工能力。在表中所列的 Full-Duplex-Bench v3 结果中，Gander 在 100 个场景上的适时接话率为 100%，提前抢话率为 6%；严格任务成功指标 Pass@1 为 0.330，低于所列基线。这说明交互时机与任务正确性需要分别考察，前者的表现不能代替对后者的评估。该评估涉及后端大脑时，使用未微调的 GPT-5.6。",
      "p.evaluation.speech": "语音对话评估从 SpokenQA 与 VoiceBench 中选取了 2,052 条语音样本。若将模型生成的语音经 ASR 转写后评分，结果会同时受到回答内容、语音合成与识别误差的影响。以 Llama Questions 为例，端到端结果为 55.87%，直接对 Thinker 输出的文本评分则为 75.60%。这两种设置用于区分语音处理环节的影响，文本结果不能直接与端到端语音结果混排比较。",
      "p.evaluation.omni": "音视频理解评估由前端直接输出文本答案。Gander 在 WorldSense 的 3,172 道题和 Daily-Omni 的 1,197 道题上，准确率分别为 49.62% 和 78.53%，均低于其初始化模型。另一方面，联合使用音频和视频优于表现更好的单一模态输入，其中 Daily-Omni 的融合增益为 19.13 个百分点。理解准确率与多模态融合收益反映不同方面的表现，需要分别解读。",
      "heading.outlook": "全模态交互智能体的挑战与未来方向",
      "p.outlook.next": "进一步提升 Gander 的协作能力，需要更准确的任务委派、更稳定的语音输出，以及大脑与小脑之间更充分的信息交换。长上下文与记忆管理、数据扩展、稳定的后训练方法和统一评估，也是后续研究的重点。这些改进将共同服务于同一个目标：让智能体在长时间、多轮次的交流中持续理解用户，并可靠地推进任务。",
      "p.perception.video": "理解一段视频，需要把当前画面与前面的情节联系起来。以下是项目提供的视频理解素材，保留了原始画面与声音。",
      "p.dialogue.robust": "在关于护照丢失的对话中，周围出现了无关人声，Gander 仍围绕当前用户的问题继续交流。这类场景要求模型结合谈话内容与上下文，判断哪些话语是对自己说的，避免被无关声音带离当前话题。",
      "toc.intro": "全模态交互智能体",
      "toc.dialogue": "音视频全双工对话",
      "toc.reasoning": "抗干扰、多人对话与简易推理",
      "toc.architecture": "大脑—小脑架构",
      "toc.streaming": "流式 Thinker–Talker",
      "toc.training": "交互数据构建",
      "toc.evaluation": "能力评估与基准测试",
      "toc.outlook": "挑战与未来方向",
      "video.visual-proactivity.title": "视觉主动交互",
      "video.visual-proactivity.caption": "记住“看到企鹅时告诉我”的要求，在企鹅出现时主动提醒。",
      "video.video-understanding.title": "视频理解",
      "video.video-understanding.caption": "视频理解素材，保留原始画面与声音。",
      "video.full-duplex.title": "全双工对话 · 附和与打断",
      "video.full-duplex.caption": "附和时继续讲述，收到明确的停止请求时暂停回应。",
      "video.robust-conversation.title": "抗干扰语音对话",
      "video.robust-conversation.caption": "在无关人声干扰下，继续讨论当前用户的护照丢失问题。",
      "video.translation-zh-en.title": "同声传译 · 中文 → 英文",
      "video.translation-zh-en.caption": "围绕版本发布与安全审计，将中文语音实时译成英文。",
      "video.translation-en-zh.title": "同声传译 · 英文 → 中文",
      "video.translation-en-zh.caption": "围绕版本发布与安全审计，将英文语音实时译成中文。",
      "video.reasoning.title": "语音常识推理",
      "video.reasoning.caption": "用语音解释：开着冰箱门，能让密闭房间降温吗？",
      "heading.collaboration": "全模态智能体交互",
      "toc.collaboration": "全模态智能体交互",
      "p.collaboration.visual": "用户先请 Gander 创建一个 HTML 俄罗斯方块游戏，再补充点击重开的功能要求，并通过共享游戏画面提出暂停按钮的配色修改。语音指令与视觉反馈贯穿同一个任务，用户可以边查看结果，边继续提出调整。",
      "p.collaboration.basic": "用户希望查找上海周边适合拍摄的地点，并比较各自的优缺点。Gander 接收语音要求后，发起后台信息搜集任务。用户在等待期间可以询问进展，Gander 查询任务状态并作出回应，随后给出地点建议。",
      "p.perception.commentary": "当用户请 Gander 解说一段旅行视频时，它会随着镜头切换，持续描述海边建筑、街巷和行人。解说内容跟随画面变化，让用户能够边看边听。",
      "p.reasoning.twoPerson": "两人讨论出游计划后，用户询问其中一人提到的出发时间。Gander 根据刚才的对话作答，将问题与相应说话人的表述对应起来。",
      "video.visual-task.title": "全模态智能体交互任务",
      "video.visual-task.caption": "通过语音创建游戏、补充功能，再结合共享画面调整按钮配色。",
      "video.collaborative-task.title": "语音智能体交互任务",
      "video.collaborative-task.caption": "查找拍摄地点、查询任务进度，并获取地点建议。",
      "video.video-commentary.title": "流式视频解说",
      "video.video-commentary.caption": "随着旅行视频的镜头变化，持续解说画面内容。",
      "video.two-person-dialogue.title": "多说话人对话理解",
      "video.two-person-dialogue.caption": "理解两人的出游讨论，回答关于出发时间的追问。",
      "video.technical-report-reading.title": "全模态智能体交互任务",
      "video.technical-report-reading.caption": "共享技术报告，发起调研与总结任务。视频中的部分内容以 5 倍速播放。",
      "p.collaboration.report": "共享屏幕上的文档，也可以直接成为任务的依据。用户展示一份技术报告，请 Gander 开展调研并整理总结。Gander 结合文档内容与口头要求发起后台任务，同时与用户确认当前材料和后续处理方向。",
      "heading.audio-agentic": "语音智能体交互",
      "toc.audio-agentic": "语音智能体交互",
      "heading.training.speech": "语音交互：学习区分打断与附和",
      "p.training.speech": "语音数据涵盖日常对话、指令遵循、问答、全双工交互与同声传译。其中，InteractionSpeech 包含 26.08 万段对话，通过主题种子生成或改写已有对话构建，并明确标注打断与附和。用户话语通过 TTS 合成为语音；助手回复保留为文本，并在时间线上标记其预计时长。每轮对话的起始时间、持续时长与重叠区间，为模型学习交互时机提供依据。最后，规则过滤与模型评审共同检查对话是否连贯、交互是否合理。",
      "heading.training.visual": "音视频交互：让回应跟上画面变化",
      "p.training.visual": "约 110 万条音视频样本来自 JoyAI-VL、LiveCC 和 Streamo，覆盖流式视频问答、视频解说与视觉主动回应。构建过程先筛选样本质量、修正时间对齐，再按平均每秒约 8 个 token 的速率调整回复长度，并将用户话语合成为语音。这些样本帮助模型持续跟踪画面中的事件与状态变化，并根据当前已观察到的信息作出回应。",
      "heading.training.agentic": "智能体交互：覆盖任务从发起到结束的全过程",
      "p.training.agentic": "智能体数据包括 32.02 万条语音智能体交互、3.6 万条全模态智能体交互，以及 0.34 万条工具辅助推理样本。语音智能体数据从分层抽取的任务种子出发，结合不同的提问与交互方式合成。全模态智能体数据则利用采集的交互记录、现有 GUI 数据集和 Codex 生成的 GUI 轨迹，提取结构化的环境与任务状态描述。DeepSeek-V4-Pro 据此生成带时间戳的用户、小脑与大脑交互轨迹，覆盖任务发起、追加要求、更新约束、澄清、进度查询、取消和结果交付，再经过一致性检查与质量筛选。",
      "heading.training.robustness": "抗干扰与负样本：学会在适当的时候保持安静",
      "p.training.robustness": "真实环境中会出现无关画面、背景噪声、重叠语音，也可能有多人同时交流。相应的训练数据覆盖这些情境，也包含没有用户指令的环境输入。其中，无关视频负样本通过将网络视频与不相关的指令配对构建；抗干扰和多人交互样本则选自高质量 Hy-Realtime 生产数据。模型需要学会忽略无关事件，在没有有效请求时保持安静，并判断是谁在说话、话语是否面向助手。",
      "figure.agentic-data.alt": "智能体数据构建流程图：上半部分从语音任务种子出发，下半部分从 GUI 视觉轨迹出发，分别合成用户、小脑与大脑的交互过程，并检查任务有效性、交互一致性和时间对齐。",
      "figure.agentic-data.caption": "图 5｜语音与全模态智能体交互数据的构建流程：准备任务种子或 GUI 轨迹，合成带时间戳的交互过程，再进行质量筛选。",
      "source.training.table": "数据分布：表 2，第 15 页",
      "source.training.agentic": "智能体数据流程：图 5，第 17 页"
    },
    "en": {
      "title": "Gander: Omni Interaction Agent",
      "subtitle": "Bringing perception, real-time conversation, and asynchronous execution together so an agent can understand requests and carry out tasks through ongoing interaction.",
      "meta.description": "Explore twelve Gander demos, from spoken and visual interaction to agentic tasks, alongside the Brain–Cerebellum architecture, interaction data construction, and evaluation results.",
      "nav.home": "Project page",
      "nav.paper": "Technical report",
      "nav.label": "Site navigation",
      "breadcrumb.home": "Gander",
      "breadcrumb.blog": "Technical blog",
      "kicker": "GANDER · TECHNICAL BLOG",
      "skip": "Skip to article",
      "lang.label": "Article language",
      "lang.zh": "切换为中文",
      "lang.en": "Switch to English",
      "meta.dateLabel": "Report date",
      "meta.date": "September 8, 2026",
      "meta.categoryLabel": "Category",
      "meta.category": "Omni interaction agent",
      "meta.byLabel": "Research team",
      "meta.by": "Hunyuan speech team\n(Research project)",
      "toc.title": "In this article",
      "toc.label": "Article contents",
      "principle.see.title": "Understand a changing environment.",
      "principle.see.body": "Interpret sound and vision together, and proactively alert the user when a relevant visual event occurs.",
      "principle.talk.title": "Follow the rhythm of conversation.",
      "principle.talk.body": "Listen while speaking, distinguish acknowledgments from interruptions and unrelated input, and decide when to continue or yield the floor.",
      "principle.act.title": "Keep tasks and conversation moving together.",
      "principle.act.body": "While complex tasks run in the background, users can still add requirements, clarify details, and check progress through speech and shared visuals.",
      "figure.overview.caption": "Figure 1. Gander’s capabilities: understanding users through continuous multimodal interaction while executing tasks asynchronously.",
      "figure.overview.alt": "Overview of Gander’s screen understanding, conversation during task execution, acknowledgments and interruptions, robust dialogue, and visual event reminders.",
      "figure.architecture.caption": "Figure 2. The roles and information exchanged between the front cerebellum, agent orchestration runtime, and back brain.",
      "figure.architecture.alt": "Brain–Cerebellum architecture: the front end receives user audio and video, the runtime coordinates background tasks, and the components share task state, context, and memory.",
      "figure.thinker-talker.caption": "Figure 4. Streaming Thinker–Talker organizes perceptual input, interaction decisions, text, and speech output on a common timeline.",
      "figure.thinker-talker.alt": "Streaming Thinker–Talker diagram showing the timing of audio-visual input, interaction control, text generation, speech tokens, and audio output.",
      "note.streaming": "One second is the duration of a processing unit; 128 chunks is the retained context window. These are architecture settings, not measurements of end-to-end response latency.",
      "video.error": "The video could not be played. Try opening it directly.",
      "video.open": "Open video",
      "source.architecture": "Architecture details: Section 3.2 of the report",
      "source.streaming": "Streaming details: Section 3.3 of the report",
      "source.training": "Data construction: Section 4, pp. 14–18",
      "source.results": "Experiments and evaluation setup: Section 5",
      "table.duplex.caption": "Full-Duplex-Bench v3 · 100 scenarios · Selected metrics from Table 3",
      "table.model": "Model",
      "table.turn": "Take-turn % ↑",
      "table.interrupt": "Interrupt % ↓",
      "table.duplex.note": "Pass@1 ranges from 0 to 1; the other metrics are percentages. ↑ Higher is better; ↓ lower is better. Interrupt is the percentage of turns in which the model starts responding before the user has finished.",
      "table.omni.caption": "Audio-visual fusion · Benchmark results from Table 6",
      "table.benchmark": "Benchmark",
      "table.av": "Audio + video %",
      "table.video": "Video only %",
      "table.audio": "Audio only %",
      "table.gain": "Fusion gain (pp)",
      "table.omni.note": "Fusion gain = joint audio-visual accuracy − max(video-only accuracy, audio-only accuracy), in percentage points. The front cerebellum answers directly in text, without speech synthesis, ASR, or the back brain.",
      "end.title": "Explore Gander further",
      "end.paper": "Read the paper",
      "end.demos": "Explore all demos",
      "footer.blog": "Technical blog",
      "footer.top": "Back to top",
      "heading.intro": "Gander: An Omni Interaction Agent",
      "p.intro.motivation": "Collaboration often means talking, observing, and acting at the same time. We acknowledge or interrupt one another, revise requests as a scene changes, and add details as work progresses. An agent that takes part in this process needs to coordinate perception, conversation, and task execution.",
      "p.intro.position": "Gander brings omni perception, real-time interaction, and agentic task execution into a single framework. It continuously receives speech, video, and text, using spoken requests, visual context, and follow-up feedback to guide ongoing work. Three capabilities shape this design:",
      "p.perception.context": "“Let me know when you see a penguin.” Gander watches the video and gives a reminder when the penguin appears. This interaction requires the model to retain an earlier request and recognize the relevant event in later frames.",
      "heading.dialogue": "Audio & Video Full-Duplex Dialogue",
      "p.dialogue.duplex": "Natural full-duplex conversation requires distinguishing an acknowledgment from a request to stop. Gander continues its explanation through brief acknowledgments, but pauses and yields the floor when the user explicitly asks it to stop. It listens during its own response and adjusts to the user’s intent.",
      "p.dialogue.translation": "Gander translates between Chinese and English as speech arrives. The examples below cover release planning, security reviews, and risk discussions, with translations produced incrementally in each direction.",
      "heading.reasoning": "Robust Dialogue, Multi-Speaker Understanding & Simple Reasoning",
      "p.reasoning.demo": "Can leaving a refrigerator door open cool a closed room? Gander explains the reasoning aloud, turning an everyday physics question into an explanation the user can follow by listening.",
      "heading.architecture": "Brain–Cerebellum Architecture",
      "p.architecture.roles": "Gander’s Brain–Cerebellum architecture divides the work among three components. The front cerebellum continuously receives audio and video, handles real-time conversation, and makes interaction decisions. The back brain handles complex reasoning, tool use, and longer tasks. Between them, an agent orchestration runtime manages task state, coordinates execution, and passes along progress and results. The back brain can be replaced without additional training for integration.",
      "p.architecture.lifecycle": "The front cerebellum uses task_start to begin background work, task_send to add instructions or request updates, and task_resolve to communicate actions such as cancellation or authorization. The orchestration runtime applies these instructions to the relevant tasks and returns progress and results to the front end. Users can therefore add constraints and revise requests while a task is underway.",
      "heading.streaming": "Streaming Thinker–Talker Modeling",
      "p.streaming.units": "The front cerebellum uses a streaming Thinker–Talker architecture with one-second processing units. Each unit first receives audio and video, along with any available text or tool results. The model then decides whether to listen, speak, interrupt, or issue a structured tool call, generating text as needed. It retains the most recent 128 chunks—roughly two minutes of context—so subsequent responses can draw on newly received information.",
      "p.streaming.speech": "The Thinker generates text and interaction actions. The Talker uses the text and hidden states to produce discrete speech units, which a streaming decoder converts into audio. In the training format, each speaking unit contains up to eight text tokens aligned with 50 S3 speech tokens. This division lets the model receive ongoing input while generating speech incrementally.",
      "heading.training": "Interaction Data Construction",
      "p.training.corpus": "Gander’s training corpus contains approximately 2.7 million examples in four families: speech interaction, audio-visual interaction, agentic interaction, and robustness and negative data. Training covers what to say, when to take a turn, how to respond to visual events, and how to handle changing task states. Together, these examples teach the model to listen, respond, and coordinate background work during ongoing conversation.",
      "heading.evaluation": "Evaluation: Interaction, Speech, and Omni Understanding",
      "p.evaluation.duplex": "The full-duplex benchmark evaluates both conversational timing and task completion. In the Full-Duplex-Bench v3 results shown below, Gander takes turns at an appropriate moment in 100% of turns and begins speaking prematurely in 6%, across 100 scenarios. Its strict task-success Pass@1 is 0.330, below the listed baselines. Timing and task correctness therefore need to be assessed separately. Where the evaluation uses the back brain, it runs GPT-5.6 without fine-tuning.",
      "p.evaluation.speech": "The spoken-conversation evaluation uses 2,052 examples from SpokenQA and VoiceBench. When synthesized replies are transcribed by ASR and then scored, the result reflects answer quality as well as speech-synthesis and recognition errors. On Llama Questions, the end-to-end score is 55.87%, compared with 75.60% when the Thinker’s text is scored directly. These settings help isolate the effects of speech processing; text-only results should not be ranked directly alongside end-to-end speech results.",
      "p.evaluation.omni": "In the audio-visual understanding evaluation, the front cerebellum answers directly in text. Gander scores 49.62% on 3,172 WorldSense questions and 78.53% on 1,197 Daily-Omni questions, both below its initialization model. Joint audio and video input nevertheless outperforms the better single modality, with a gain of 19.13 percentage points on Daily-Omni. Understanding accuracy and the benefit of combining modalities measure different aspects of performance and should be read separately.",
      "heading.outlook": "Challenges and Future Directions for Omni Interaction Agents",
      "p.outlook.next": "Further progress calls for more accurate task delegation, more reliable speech output, and richer information exchange between the brain and cerebellum. Longer context, memory management, larger datasets, stable post-training methods, and unified evaluation are also priorities. Together, these improvements aim to make the agent a more dependable collaborator over extended conversations and tasks.",
      "p.perception.video": "Understanding video requires relating the current scene to what came before. The source clip below accompanies the project’s video-understanding example and retains its original visuals and audio.",
      "p.dialogue.robust": "Unrelated voices enter a conversation about a lost passport, but Gander stays focused on the current user’s question. This setting calls for using conversational context to determine which speech is addressed to the assistant and which belongs to the surrounding environment.",
      "toc.intro": "Omni interaction agent",
      "toc.dialogue": "Audio & video full-duplex dialogue",
      "toc.reasoning": "Robust dialogue, multi-speaker understanding & simple reasoning",
      "toc.architecture": "Brain–Cerebellum architecture",
      "toc.streaming": "Streaming Thinker–Talker",
      "toc.training": "Interaction data construction",
      "toc.evaluation": "Evaluation benchmarks",
      "toc.outlook": "Challenges and future directions",
      "video.visual-proactivity.title": "Proactive visual interaction",
      "video.visual-proactivity.caption": "Remember the request to watch for a penguin and give a reminder when it appears.",
      "video.video-understanding.title": "Video understanding",
      "video.video-understanding.caption": "Source clip for video understanding, with its original visuals and audio.",
      "video.full-duplex.title": "Full-duplex dialogue · Backchannels and interruptions",
      "video.full-duplex.caption": "Continue through acknowledgments; pause when the user explicitly asks to stop.",
      "video.robust-conversation.title": "Interference-resistant spoken dialogue",
      "video.robust-conversation.caption": "Stay focused on the user’s question about a lost passport despite unrelated speech nearby.",
      "video.translation-zh-en.title": "Simultaneous Translation · Chinese → English",
      "video.translation-zh-en.caption": "Translate spoken Chinese into English during a discussion of release planning and security reviews.",
      "video.translation-en-zh.title": "Simultaneous Translation · English → Chinese",
      "video.translation-en-zh.caption": "Translate spoken English into Chinese during a discussion of release planning and security reviews.",
      "video.reasoning.title": "Spoken commonsense reasoning",
      "video.reasoning.caption": "Explain aloud whether an open refrigerator can cool a closed room.",
      "heading.collaboration": "Omni Agentic Interaction",
      "toc.collaboration": "Omni agentic interaction",
      "p.collaboration.visual": "The user asks Gander to create an HTML Tetris game, adds a click-to-restart feature, and then shares the game screen to request a different pause-button color. Spoken instructions and visual feedback guide the same task, allowing the user to review the result and request further changes as work progresses.",
      "p.collaboration.basic": "The user asks Gander to find filming locations near Shanghai and compare their pros and cons. Gander starts the research in the background. When the user asks for an update, it checks the task status and responds, then returns location suggestions as the work concludes.",
      "p.perception.commentary": "Asked to narrate a travel video, Gander describes coastal buildings, streets, and people as the camera moves between scenes. The commentary follows the changing view, so the user can watch and listen at the same time.",
      "p.reasoning.twoPerson": "After two people discuss an outing, the user asks about a departure time proposed by one of the speakers. Gander answers from the preceding conversation, connecting the question to the relevant speaker’s statement.",
      "video.visual-task.title": "Omni agentic interaction task",
      "video.visual-task.caption": "Create a game by voice, add a feature, and use the shared screen to request a new button color.",
      "video.collaborative-task.title": "Audio agentic interaction task",
      "video.collaborative-task.caption": "Research filming locations, check progress, and receive location suggestions.",
      "video.video-commentary.title": "Streaming video commentary",
      "video.video-commentary.caption": "Narrate a travel video as the camera moves between scenes.",
      "video.two-person-dialogue.title": "Multi-speaker dialogue understanding",
      "video.two-person-dialogue.caption": "Follow a two-person conversation and answer a question about the proposed departure time.",
      "video.technical-report-reading.title": "Omni agentic interaction task",
      "video.technical-report-reading.caption": "Share a technical report and start a research-and-summary task. Parts of the video play at 5× speed.",
      "p.collaboration.report": "A document on screen can provide the context for a task. The user shares a technical report and asks Gander to research it and prepare a summary. Gander uses the document and spoken request to start a background task, while confirming the material and next steps with the user.",
      "heading.audio-agentic": "Audio Agentic Interaction",
      "toc.audio-agentic": "Audio agentic interaction",
      "heading.training.speech": "Speech Interaction: Interruptions and Backchannels",
      "p.training.speech": "Speech data cover everyday dialogue, instruction following, question answering, full-duplex interaction, and simultaneous translation. InteractionSpeech contains 260.8K dialogues generated from topic seeds or adapted from existing conversations, with explicit labels for interruptions and backchannels. User turns are synthesized with TTS; assistant turns remain as text with assigned durations on the timeline. Turn onsets, durations, and overlap intervals provide supervision for interaction timing. Rule-based filtering and model review then check conversational coherence and interaction quality.",
      "heading.training.visual": "Audio-Visual Interaction: Keeping Responses in Step with the Scene",
      "p.training.visual": "Approximately 1.1 million examples from JoyAI-VL, LiveCC, and Streamo cover streaming video question answering, narration, and proactive visual responses. The construction process filters for quality and corrects temporal alignment. Responses are then rewritten to average 8 tokens per second, and user utterances are synthesized as speech. The resulting examples teach the model to track events and state changes and respond using information it has observed so far.",
      "heading.training.agentic": "Agentic Interaction: From Task Initiation to Completion",
      "p.training.agentic": "Agentic data include 320.2K audio agentic examples, 36K omni agentic examples, and 3.4K tool-assisted reasoning examples. Audio agentic examples combine hierarchically sampled task seeds with varied questions and interaction patterns. Omni agentic examples use collected interactions, existing GUI datasets, and Codex-generated GUI trajectories, converted into structured descriptions of environment and task states. DeepSeek-V4-Pro uses these inputs to generate timestamped interactions among the user, cerebellum, and brain. The trajectories cover task initiation, follow-up requests, constraint updates, clarification, progress queries, cancellation, and result delivery. They are then checked for consistency and filtered for quality.",
      "heading.training.robustness": "Robustness and Negative Data: Knowing When to Stay Silent",
      "p.training.robustness": "Real environments contain unrelated visuals, background noise, overlapping speech, and conversations among several people. This data family covers those conditions as well as input without a user command. Irrelevant-video negatives pair web videos with unrelated instructions; interference and multi-party examples come from high-quality Hy-Realtime production data. The model learns to ignore unrelated events, remain silent without a valid request, and identify who is speaking and whether they are addressing the assistant.",
      "figure.agentic-data.alt": "Agentic data construction diagram: the upper pipeline starts with audio task seeds and the lower pipeline with GUI visual trajectories. Both synthesize user, cerebellum, and brain interactions and check task validity, interaction coherence, and temporal alignment.",
      "figure.agentic-data.caption": "Figure 5. Building audio and omni agentic interaction data: prepare task seeds or GUI trajectories, synthesize timestamped interactions, and filter for quality.",
      "source.training.table": "Data distribution: Table 2, p. 15",
      "source.training.agentic": "Agentic data pipeline: Figure 5, p. 17"
    }
  },
  "sections": [
    "intro",
    "collaboration",
    "audio-agentic",
    "dialogue",
    "reasoning",
    "architecture",
    "streaming",
    "training",
    "evaluation",
    "outlook"
  ]
};
